### ISSUE TITLE
Bug in FARTSSIE28

### ISSUE THREAD

**Issue by meet2341991** [dndubins/FARTSSIE#1]
I found a bug in calculating ISV for Bioequivalence, replicate @dndubins

**Comment by dndubins** [comment]
Thanks! Can you be more specific? What was the bug? What platform are you using? Did you enable macros?

**Comment by meet2341991** [comment]
Hey David,

Thanks for getting back to me.

I enabled the macros. Error 13 appeared. I’ll send more details tomorrow
when I get back to work. I was calculating ISV for BE replicate design and
got bug.

Regards,
Meet shah

**Comment by dndubins** [comment]
Thank you, I believe I have fixed this bug. Please re-download FARTSSIE and try it again on your end to confirm. Thanks!
